### ISSUE TITLE
New pip release

### ISSUE THREAD

**Issue by Fryyyyy** [log2timeline/dfimagetools#110]
Last pip package was from 7 months ago, can we please make a new one to incorporate some fixes made since then?

**Comment by joachimmetz** [comment]
Per chat you need the changes in https://github.com/log2timeline/dfimagetools/commit/8c22542940fc50c49016882fa51633ee682f1c81

**Comment by joachimmetz** [comment]
https://github.com/log2timeline/dfimagetools/releases/tag/20241116
